/**
 * Every mutation of application state, each one persisting as it goes.
 *
 * Kept separate from state.js because storage.js already imports state.js —
 * putting the writes here keeps the module graph acyclic, and it gives the
 * screens one vocabulary to call instead of reaching into state directly.
 */

import { goalSaved, newId, state } from './state.js';
import { save } from './storage.js';
import { todayLocalISO } from './utils/date.js';

/* ---------------------------------------------------------- transactions -- */

export function addTransaction({ name, amount, category, date, note = '', billId = null }) {
    const txn = { id: newId(), name, amount, category, date, note };
    if (billId) txn.billId = billId;
    state.transactions.push(txn);
    save();
    return txn;
}

export function updateTransaction(id, patch) {
    const txn = state.transactions.find((t) => t.id === id);
    if (!txn) return null;
    Object.assign(txn, patch);
    save();
    return txn;
}

export function removeTransaction(id) {
    const idx = state.transactions.findIndex((t) => t.id === id);
    if (idx === -1) return;
    const [removed] = state.transactions.splice(idx, 1);
    // A transaction generated by paying a bill is the record of that payment,
    // so deleting it puts the bill back on the unpaid list.
    if (removed.billId) {
        const bill = state.bills.find((b) => b.id === removed.billId);
        if (bill) bill.paid = false;
    }
    save();
}

export const getTransaction = (id) => state.transactions.find((t) => t.id === id) ?? null;

/* ----------------------------------------------------------------- bills -- */

export function addBill({ name, amount, due }) {
    const bill = { id: newId(), name, amount, due, paid: false };
    state.bills.push(bill);
    save();
    return bill;
}

/**
 * Marking a bill paid records the payment as a transaction, so the money
 * actually leaves the balance and counts against the budget. Previously this
 * only flipped a flag and the budget never noticed.
 */
export function setBillPaid(id, paid) {
    const bill = state.bills.find((b) => b.id === id);
    if (!bill || bill.paid === paid) return;
    bill.paid = paid;

    if (paid) {
        const txn = addTransaction({
            name: bill.name,
            amount: -Math.abs(bill.amount),
            category: 'Bills',
            // Dated when it was paid, not when it was due, so it lands in the
            // budget month the money actually left.
            date: todayLocalISO(),
            note: 'Bill payment',
            billId: bill.id,
        });
        bill.txnId = txn.id;
    } else if (bill.txnId) {
        const idx = state.transactions.findIndex((t) => t.id === bill.txnId);
        if (idx !== -1) state.transactions.splice(idx, 1);
        delete bill.txnId;
    }
    save();
}

export function removeBill(id) {
    const bill = state.bills.find((b) => b.id === id);
    if (!bill) return;
    if (bill.txnId) {
        const idx = state.transactions.findIndex((t) => t.id === bill.txnId);
        if (idx !== -1) state.transactions.splice(idx, 1);
    }
    state.bills = state.bills.filter((b) => b.id !== id);
    save();
}

/* ------------------------------------------------------- goals & savings -- */

export function addGoal({ name, target, due }) {
    const goal = { id: newId(), name, target, due };
    state.goals.push(goal);
    save();
    return goal;
}

export function addContribution(goalId, amount) {
    const contribution = { id: newId(), goalId, amount, date: todayLocalISO() };
    state.contributions.push(contribution);
    save();
    return contribution;
}

/** Removing a goal removes its contributions, so the chart can't outlive it. */
export function removeGoal(id) {
    state.goals = state.goals.filter((g) => g.id !== id);
    state.contributions = state.contributions.filter((c) => c.goalId !== id);
    save();
}

export const savedForGoal = (goalId) => goalSaved(state, goalId);

/* ------------------------------------------------------------ categories -- */

export function addCategory(name) {
    const clean = name.trim();
    if (!clean || state.categories.some((c) => c.toLowerCase() === clean.toLowerCase())) {
        return state.categories.find((c) => c.toLowerCase() === clean.toLowerCase()) ?? null;
    }
    state.categories.push(clean);
    save();
    return clean;
}

/* --------------------------------------------------------------- budget --- */

export function setMonthlyBudget(amount) {
    state.monthlyBudget = Math.max(0, amount);
    save();
}

export function setPeriod(period) {
    state.period = period;
    save();
}

export function setViewDate(iso) {
    state.viewDate = iso;
    save();
}
